name: dbt_project

profile: next_station

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt_project:
    +schema: raw

vars:
  h3_resolution: 8

models:
  dbt_project:
    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
